app.beginUndoGroup("WeatherCG");
var proj=app.project;
var dir="C:/WCG/frames/sid01";
var comp=proj.items.addComp("WeatherCG_20261007_0930",1920,1080,1.0,6.000000,29.970000);
var TG=comp;
function imp(f){var io=new ImportOptions(File(dir+"/"+f));return proj.importFile(io);}
function addL(f,nm){var l=TG.layers.add(imp(f));l.name=nm;return l;}
function hx(h){h=String(h).replace("#","");return [parseInt(h.substr(0,2),16)/255,parseInt(h.substr(2,2),16)/255,parseInt(h.substr(4,2),16)/255];}
function addT(txt,nm){var l=TG.layers.addText(txt);l.name=nm;return l;}
function ez2(prop){var A=[new KeyframeEase(0,33)],B=[new KeyframeEase(0,75)];try{prop.setInterpolationTypeAtKey(1,KeyframeInterpolationType.BEZIER,KeyframeInterpolationType.BEZIER);prop.setInterpolationTypeAtKey(2,KeyframeInterpolationType.BEZIER,KeyframeInterpolationType.BEZIER);prop.setTemporalEaseAtKey(1,A,A);prop.setTemporalEaseAtKey(2,B,B);}catch(err){}}
function fadeL(l,s,e){var op=l.property("Opacity");op.setValueAtTime(s,0);op.setValueAtTime(e,100);ez2(op);}
function ezR(prop){try{var n=1;try{n=prop.value.length||1;}catch(e){n=1;}var A=[],B=[];for(var i=0;i<n;i++){A.push(new KeyframeEase(0,33));B.push(new KeyframeEase(0,75));}prop.setInterpolationTypeAtKey(1,KeyframeInterpolationType.BEZIER,KeyframeInterpolationType.BEZIER);prop.setInterpolationTypeAtKey(2,KeyframeInterpolationType.BEZIER,KeyframeInterpolationType.BEZIER);prop.setTemporalEaseAtKey(1,A,A);prop.setTemporalEaseAtKey(2,B,B);}catch(err){}}
function dshadow(l){try{var e=l.property("ADBE Effect Parade").addProperty("ADBE Drop Shadow");e.property("Shadow Color").setValue(hx("#000814"));e.property("Opacity").setValue(114.750000);e.property("Direction").setValue(180.000000);e.property("Distance").setValue(8.000000);e.property("Softness").setValue(20.000000);}catch(err){}}
var LG0=proj.items.addComp("\ubc94\ub840",100,1,1.0,6.000000,29.970000);
(function(){var sl=LG0.layers.addShape();sl.name="\ubc94\ub840 1_\ub124\ubaa8";var root=sl.property("ADBE Root Vectors Group");var vg=root.addProperty("ADBE Vector Group");var ct=vg.property("ADBE Vectors Group");var rc=ct.addProperty("ADBE Vector Shape - Rect");rc.property("ADBE Vector Rect Size").setValue([1.000000,1.000000]);rc.property("ADBE Vector Rect Roundness").setValue(0.000000);var fl=ct.addProperty("ADBE Vector Graphic - Fill");fl.property("ADBE Vector Fill Color").setValue(hx("#123456"));sl.property("Anchor Point").setValue([0,0]);sl.property("Position").setValue([0.500000,0.500000]);})();
(function(){var tl=LG0.layers.addText("\uccab\uc9f8");tl.name="\ubc94\ub840 1_\uae00\uc790";var d=tl.property("Source Text").value;d.fontSize=30;d.applyFill=true;try{d.applyStroke=false;}catch(e){}d.fillColor=hx("#FFFFFF");try{d.font="SUITE-SemiBold";}catch(e){}try{d.justification=ParagraphJustification.LEFT_JUSTIFY;}catch(e){}try{d.tracking=0.000000;}catch(e){}tl.property("Source Text").setValue(d);var r=tl.sourceRectAtTime(0,false);tl.property("Anchor Point").setValue([r.left,r.top+r.height/2]);tl.property("Position").setValue([0.000000,0.500000]);})();
(function(){var sl=LG0.layers.addShape();sl.name="\ubc94\ub840 2_\ub124\ubaa8";var root=sl.property("ADBE Root Vectors Group");var vg=root.addProperty("ADBE Vector Group");var ct=vg.property("ADBE Vectors Group");var rc=ct.addProperty("ADBE Vector Shape - Rect");rc.property("ADBE Vector Rect Size").setValue([1.000000,1.000000]);rc.property("ADBE Vector Rect Roundness").setValue(0.000000);var fl=ct.addProperty("ADBE Vector Graphic - Fill");fl.property("ADBE Vector Fill Color").setValue(hx("#FFFFFF"));sl.property("Anchor Point").setValue([0,0]);sl.property("Position").setValue([0.500000,0.500000]);})();
(function(){var tl=LG0.layers.addText("");tl.name="\ubc94\ub840 2_\uae00\uc790";var d=tl.property("Source Text").value;d.fontSize=30;d.applyFill=true;try{d.applyStroke=false;}catch(e){}d.fillColor=hx("#FFFFFF");try{d.font="SUITE-SemiBold";}catch(e){}try{d.justification=ParagraphJustification.LEFT_JUSTIFY;}catch(e){}try{d.tracking=0.000000;}catch(e){}tl.property("Source Text").setValue(d);var r=tl.sourceRectAtTime(0,false);tl.property("Anchor Point").setValue([r.left,r.top+r.height/2]);tl.property("Position").setValue([0.000000,0.500000]);})();
(function(){var sl=LG0.layers.addShape();sl.name="\uc13c\ud130\uc5c6\uc74c_\ub124\ubaa8";var root=sl.property("ADBE Root Vectors Group");var vg=root.addProperty("ADBE Vector Group");var ct=vg.property("ADBE Vectors Group");var rc=ct.addProperty("ADBE Vector Shape - Rect");rc.property("ADBE Vector Rect Size").setValue([0.100000,0.100000]);rc.property("ADBE Vector Rect Roundness").setValue(0.000000);var fl=ct.addProperty("ADBE Vector Graphic - Fill");fl.property("ADBE Vector Fill Color").setValue(hx("#FFFFFF"));sl.property("Anchor Point").setValue([0,0]);sl.property("Position").setValue([1.550000,2.550000]);})();
(function(){var tl=LG0.layers.addText("c");tl.name="\uc13c\ud130\uc5c6\uc74c_\uae00\uc790";var d=tl.property("Source Text").value;d.fontSize=1;d.applyFill=true;try{d.applyStroke=false;}catch(e){}d.fillColor=hx("#FFFFFF");try{d.font="SUITE-SemiBold";}catch(e){}try{d.justification=ParagraphJustification.LEFT_JUSTIFY;}catch(e){}try{d.tracking=0.000000;}catch(e){}tl.property("Source Text").setValue(d);var r=tl.sourceRectAtTime(0,false);tl.property("Anchor Point").setValue([r.left,r.top+r.height/2]);tl.property("Position").setValue([3.000000,0.500000]);})();
(function(){var sl=LG0.layers.addShape();sl.name="\ubc94\ub840 4_\ub124\ubaa8";var root=sl.property("ADBE Root Vectors Group");var vg=root.addProperty("ADBE Vector Group");var ct=vg.property("ADBE Vectors Group");var rc=ct.addProperty("ADBE Vector Shape - Rect");rc.property("ADBE Vector Rect Size").setValue([1.000000,1.000000]);rc.property("ADBE Vector Rect Roundness").setValue(0.000000);var fl=ct.addProperty("ADBE Vector Graphic - Fill");fl.property("ADBE Vector Fill Color").setValue(hx("#FFFFFF"));sl.property("Anchor Point").setValue([0,0]);sl.property("Position").setValue([0.500000,0.500000]);})();
(function(){var tl=LG0.layers.addText("");tl.name="\ubc94\ub840 4_\uae00\uc790";var d=tl.property("Source Text").value;d.fontSize=30;d.applyFill=true;try{d.applyStroke=false;}catch(e){}d.fillColor=hx("#FFFFFF");try{d.font="SUITE-SemiBold";}catch(e){}try{d.justification=ParagraphJustification.LEFT_JUSTIFY;}catch(e){}try{d.tracking=0.000000;}catch(e){}tl.property("Source Text").setValue(d);var r=tl.sourceRectAtTime(0,false);tl.property("Anchor Point").setValue([r.left,r.top+r.height/2]);tl.property("Position").setValue([0.000000,0.500000]);})();
var L0=TG.layers.add(LG0);L0.name="\ubc94\ub840";
L0.property("Position").setValue([0.000000,0.000000]);
comp.openInViewer();app.endUndoGroup();